// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSIn3PWhGDXPQxGUOUanxtxdBhmdS8THs',
    appId: '1:673951693624:web:87c562e732cb5c82fa9fcd',
    messagingSenderId: '673951693624',
    projectId: 'harley-7fc6e',
    authDomain: 'harley-7fc6e.firebaseapp.com',
    storageBucket: 'harley-7fc6e.firebasestorage.app',
    measurementId: 'G-VV33PXYFCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbN33sIJLj7Fe5IBVHDBH-X1F0HS8i4tU',
    appId: '1:673951693624:android:4f0ac8ff5dd69aebfa9fcd',
    messagingSenderId: '673951693624',
    projectId: 'harley-7fc6e',
    storageBucket: 'harley-7fc6e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSIn3PWhGDXPQxGUOUanxtxdBhmdS8THs',
    appId: '1:673951693624:web:ff6d087388ed8c2ffa9fcd',
    messagingSenderId: '673951693624',
    projectId: 'harley-7fc6e',
    authDomain: 'harley-7fc6e.firebaseapp.com',
    storageBucket: 'harley-7fc6e.firebasestorage.app',
    measurementId: 'G-BSL0MRT9RP',
  );
}
